version: '3'
services: 
    redis:
        image: redis
        ports: 
            - 6379:6379
    worker:
        depends_on: 
            - redis
        build:
            context: ./worker
            dockerfile: Dockerfile
        environment: 
            PORT: 3000
            SECRET_KEY: "secretKey"
            REDIS_URL: "redis://redis:6379"
            GATEKEEPER_URL: "https://dev.tamudatathon.com/auth"
            STOCK_PROBLEM_TEST_FILE: "/secret/test.csv"
            HOST_KOTH_WORKER_ROOT: $PWD/worker
            GOOGLE_APPLICATION_CREDENTIALS: "/keys/firebase-creds.json"
        env_file:
            - ./.env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../test-cases:/secret
            - ../keys:/keys
        ports:
            - 4000:3000