version: '3'
services: 
    redis:
        image: redis
        ports: 
            - 6379:6379
    worker:
        depends_on: 
            - redis
        build:
            context: ./worker
            dockerfile: Dockerfile
        environment: 
            PORT: 3000
            SECRET_KEY: "secretKey"
            REDIS_URL: "redis://redis:6379"
        volumes:
            - ./worker:/workspace
            - /var/run/docker.sock:/var/run/docker.sock